### ISSUE TITLE
Call to a member function getAdditionalInformation()

### ISSUE THREAD

**Issue by mortenjakobsen** [ePay/magento#30]
I see this error a lot, in the PHP-errorlog - it appears multiple times every day.

We experience customers that doesn't get redirected to the payment window - I assume it's related to this.

PHP Fatal error:  Call to a member function getAdditionalInformation() on boolean in /app/code/local/Mage/Epay/controllers/StandardController.php on line 43

Line 43 is this call:

`$pspReference = $payment->getAdditionalInformation(Mage_Epay_Model_Standard::PSP_REFERENCE);`

**Comment by Aplbo** [comment]
I see this in our logs too, but I can't relate the error 1:1 to payment issues, as there are time differences between order placement and the log entry.
It looks like the error is triggered, because of the way ```$payment``` is checked. ```getAdditionalInformation()``` CAN return a boolean, but this isn't expected in the StandardController. 
I'd suggest to check for the specific object type on line 42 (e.g. ```if($payment instanceof Mage_Payment_Model_Info)```), but I dont know enough about the payment flow in Magento to make a pull request.

**Comment by AllanWLie** [comment]
Hi,

We will look into the issue. 

Could you both please provide the Magento and PHP version you are using ?

Thank you.

**Comment by mortenjakobsen** [comment]
Sounds great :-)

Here's the info:
- Magento ver. 1.9.1.1
- PHP Version 5.6.30

**Comment by Aplbo** [comment]
Sounds really good. 
I'm running 
- Magento 1.9.1.0 
- PHP 5.6.31

**Comment by AllanWLie** [comment]
Hi all,

We have now corrected the issue. 
Link to new version: https://github.com/ePay/magento/releases/latest

Thank you both, for your inputs to resolving this issue. 

**Best regards**
Allan Lie
