### ISSUE TITLE
Unsafe use of strpos, Travis code sniffer jobs disabled

### ISSUE THREAD

**Issue by kim-sondrup** [ePay/magento#38]
Have spotted a unsafe use of strpos in a commit from about a month back [`2ea81b5`](https://github.com/ePay/magento/commit/2ea81b59829e739c32093a06084d2ddcd9144d79#diff-415a60ad1fc6ec1575c7e231c94eb7e6R39)

By what looks like a misunderstanding Travis have been disabled instead of correcting this 5ff86ff69196eb297cc984d85d861767aa82257f

Magento PHP doc write a warning about using strpos without === (triple equal) operators http://php.net/manual/en/function.strpos.php  

Magento Marketplace's code sniffer tool tells about this problem https://travis-ci.org/ePay/magento/jobs/394935712#L522-L523
  
ECG Magento Code Sniffer tells about this problems https://travis-ci.org/ePay/magento/jobs/394935714#L718-L719

**Comment by AllanWLie** [comment]
Hi @kim-sondrup

Thank you for correcting this. But your last commit "f029327" should not be:
if (empty($truncatedCardNumber) || strpos($truncatedCardNumber, 'XXXX') !== false)

but instead

if (empty($truncatedCardNumber) || strpos($truncatedCardNumber, 'XXXX') === false)

So that if the "truncatedCardNumber" do not contain 'XXXX' then it should fetch it from the database since the decryption failed.

Please correct this so that I can Accept your pull request.

Best regards
Allan - Bambora
