### ISSUE TITLE
Feature Request: Send Payment Request Link using Magento email template

### ISSUE THREAD

**Issue by mikkelsiggaard** [ePay/magento#47]
Will it be possible to add a feature, where it is possible (from Magento Backend) to send the payment link in a shop specific email template? 

The content included in this email could be very similar to an order confirmation in layout and what information is included.

This would be a more professional solution than manually sending an email, from a personal email address rather than the default shop email address.

**Comment by AllanWLie** [comment]
Hi @mikkelsiggaard,

It is not possible to add this feature since the payment link send to the customer is generated in our payment system and not in the Magento shop. It would require a major restructuring of the payment request feature in the payment system.

Thank you and have a good day.

Best regards
Allan - Bambora Online

**Comment by mikkelsiggaard** [comment]
Hi @AllanWLie, 

Thank you for your quick and informative reply. 

I can see that is not a valid solution then.
