### ISSUE TITLE
Feature Request: Access to "Epay Payment Request"

### ISSUE THREAD

**Issue by mikkelsiggaard** [ePay/magento#48]
There already is the option for admins to get a payment link related to an order that has not yet been paid. 
However, this is not possible to add to other user roles in Magento. 
It does seem like an irregularity with the Access Control List.

**Comment by AllanWLie** [comment]
Hi @mikkelsiggaard 

Currently only the admin user can use the payment request feature and it have been like this since we made the feature but it is on our list of feature requests to the module to open up for custom user roles for this feature. If and when it will be implemented is at this time uncertain.

Thank you and a good day to you.

Best regards
Allan - Bambora Online

**Comment by mikkelsiggaard** [comment]
Hi @AllanWLie, 

Okay, sounds good. I hope it gets implemented. 

You have a good day to!
